### ISSUE TITLE
Feature: Link d-portal to the IATI Validator

### ISSUE THREAD

**Issue by amy-silcock** [IATI/D-Portal#636]
**Use case:** Publishers often check d-portal to ensure their data is displaying correctly. To further this, a link from each activity to it's file's validation page could be added.

**Design:**
Link to the IATI Validator results page to be added to the following bar:
![image](https://user-images.githubusercontent.com/27764077/145032973-0e3510f3-eed6-462e-b2c2-7a5cc1fbb481.png)

E.g. this activity [XM-DAC-41121-2021-EHGL](http://d-portal.org/ctrack.html?reporting_ref=XM-DAC-41121#view=act&aid=XM-DAC-41121-2021-EHGL) should link to the following Validator [results page](https://iativalidator.iatistandard.org/view/dqf/files/d4239611-9fca-4589-9200-b3871a688824) (this page is for the file UNHCR-Activities-2022.xml)

Note, that the URL for the validator page changes each time the file is updated and the hash changes in the IATI Registry.

**Comment by notshi** [comment]
Hi @amy-silcock - this feature is now live on d-portal.

> Note, that the URL for the validator page changes each time the file is updated and the hash changes in the IATI Registry.

However, the number used in the url is not a hash (or a checksum). It is an internal CKAN id that does not change when the files content changes.

We are not sure why the validator is using this CKAN id as opposed to the dataset slug that is already currently being used for the Registry.

As such, we have had to create an additional lookup table so that we can change the dataset slug into this new validator id link.

We suggest the validator team to take a look at this and use the actual hash since that seems to be the original intention. If that is no longer the case, please use the dataset slug.

**Comment by amy-silcock** [comment]
Great to see this implemented! I'll pass your feedback over to our devs to have a look at
