### ISSUE TITLE
Participating Org page : "IATI Organisations"

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#672]
Thanks to the good work of https://github.com/IATI/D-Portal/issues/669 we've a something else that may jar: IATI Organisations (was IATI Publishers)

![Firefox_Screenshot_2024-04-08T07-42-23 451Z](https://github.com/IATI/D-Portal/assets/1209944/f51d3851-eb0d-4fc4-a0b6-62168404f710)

https://d-portal.org/ctrack.html?/participating-org@ref=DK-CVR-44623528#view=list_publishers

![Firefox_Screenshot_2024-04-08T07-48-24 647Z](https://github.com/IATI/D-Portal/assets/1209944/0a5038b5-1c1a-439f-a6e4-67d5c3f0ed16)

Idea would be this is "IATI Reporting Orgs" I think

IATI Organisations has connotations in other parts of the standard that are moribund - eg https://iatistandard.org/en/iati-standard/203/codelists/organisationidentifier/

@notshi is this label "Organisations" because we asked for

> when a participating-org/@ref page has a know reporting-org/@ref: "View activities reported by this organisation" 

maybe?

/cc @isabelbirds

Thanks

**Comment by notshi** [comment]
Yes, this is a knock on effect from #670 - wasn't sure if we should be using Reporting Organisations, Reporting organisations, reporting organisation/s, or Reporting Orgs with similar variations of lowercase and/or capitals.

So we err on the side of caution and went with 'change it when raised in issues'.

> Idea would be this is "IATI Reporting Orgs" I think

But yes, agree this should be as the standard; ie. Reporting Orgs since we now have Participating Orgs.

Change is now live on the site.

**Comment by stevieflow** [comment]
Perfect, thanks @notshi

**Comment by stevieflow** [comment]
Agreed - this should be Organisation(s) rather than Org(s) @notshi

**Comment by notshi** [comment]
This change is now live.
